### PR TITLE
Verification PR, not for merging

### PR DESCRIPTION
**Pull request by Szasza**
This pull request is created in order to verify the general direction of the API documentation.

I would like to ask to please review the Endpoints/Games page, add a comment to the pull request if the direction is good or not, but please do not merge it just yet because it contains non-existent links.

Thank you for your help.

### CODE REVIEW

**Comment by krazyjakee** [comment]
A fantastic contribution and I agree with your idea of spreading out the endpoints to be more easily consumed. Thank you for this. Just comment when you are happy with progress and I will merge.

**Comment by Szasza** [comment]
Awesome, thank you for the quick response and for the confirmation. I will keep you updated, my expectation is to have all the pages done by Sunday.

**Comment by Szasza** [comment]
@krazyjakee the PR can be reviewed and merged at your earliest convenience.

Please let me know if there are any problems.

**Comment by krazyjakee** [comment]
Words cannot describe. Again, fantastic work and thank you very much indeed. From monday we will look into the issues you have raised on mashape to improve the API.

**Comment by Szasza** [comment]
You're welcome and thank you for addressing the suggestions 🎉

**Pull request merged**
